### ISSUE TITLE
Plugin does not load on Xcode 6.4

### ISSUE THREAD

**Issue by SteveCaine** [nanaimostudio/Xcode-Quick-Localization#14]
This appears to be a repeat of issue #2, where a new version of Xcode refuses to load (some?) third-party plugins. After installing Xcode 6.4 and making it the active version using the command 'xcode-select', I get this warning when running Xcode from the command line:

xcodebuild [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/QuickLocalization.xcplugin' not present in DVTPlugInCompatibilityUUIDs

The fix last time was an update to the plugin's Info.plist file. Same answer here?

**Comment by caoer** [comment]
@SteveCaine  yes, have to update the UUID everytime Xcode updates.
it should be fixed in https://github.com/nanaimostudio/Xcode-Quick-Localization/commit/8a19072dd8b6b99928bf8c8983869c7ab89c45fb

However due to my current project need to use 6.3.2, I haven't got the chance to test on 6.4. If it does not work, pleaes let me know. THANKS!
