### ISSUE TITLE
Crashes on Xcode 7.0.1 (7A1001)

### ISSUE THREAD

**Issue by kivannc** [nanaimostudio/Xcode-Quick-Localization#20]
When the shortcut is used Xcode freezes right away.

**Comment by caoer** [comment]
@kivannc can you send the crash log?

**Comment by caoer** [comment]
@kivannc I forgot to set the inital format string. crash issue is fixed in 2616d59a64c6d85ed4b35ece6ffb6a92a3d1567a. can you try again? 
this can also be fixed if open the setting panel and choose a format string manually. 

If still crashing, please send me the crash log, I will look into it. :8ball:

**Comment by caoer** [comment]
@kivannc closing it due to inactivity. :last_quarter_moon_with_face:

**Comment by kivannc** [comment]
Sorry I was really busy this week i will try the solution and if I got the
crash i will send you to report.

**Comment by caoer** [comment]
@kivannc cool, thanks for the updates :+1:  :1234:
